package com.bluetalk.app.data

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Delivery lifecycle of an outgoing message, mirroring the familiar
 * messenger tick states: pending (queued, peer unreachable), sent
 * (written to the Bluetooth socket), delivered (acknowledged by the
 * peer's device) and read (peer opened the conversation).
 */
enum class MessageStatus { PENDING, SENT, DELIVERED, READ }

/**
 * A conversation: either a 1:1 chat (keyed by a device MAC or BLE peer id)
 * or a group (keyed by a random group id, [isGroup] true).
 */
@Entity(tableName = "conversations")
data class Conversation(
    @PrimaryKey val address: String,
    val name: String,
    val lastActivity: Long,
    /** True for group conversations. */
    val isGroup: Boolean = false,
    /** JSON array of member peer ids, for groups. */
    val memberIds: String? = null,
    /** The remote peer's announced install-stable id, for 1:1 contacts. */
    val peerId: String? = null,
)

@Entity(
    tableName = "messages",
    indices = [Index(value = ["conversationAddress", "timestamp"])],
)
data class Message(
    /** Random UUID generated by the sender; also used to de-duplicate re-sends. */
    @PrimaryKey val id: String,
    val conversationAddress: String,
    val body: String,
    val timestamp: Long,
    val isMine: Boolean,
    /** Only meaningful for outgoing messages. */
    val status: MessageStatus,
    /** Whether the local user has seen this message (drives the unread badge). */
    val isRead: Boolean,
    /** Local path to an attached file/image, or null for a plain text message. */
    val attachmentPath: String? = null,
    /** Original file name of the attachment. */
    val attachmentName: String? = null,
    /** MIME type of the attachment (e.g. "image/jpeg"). */
    val attachmentMime: String? = null,
    /** Display name of the sender, for incoming group messages. */
    val senderName: String? = null,
)

/** Row shape for the conversation list: conversation plus preview and unread count. */
data class ConversationSummary(
    val address: String,
    val name: String,
    val lastActivity: Long,
    val isGroup: Boolean,
    val lastMessage: String?,
    val lastMessageIsMine: Boolean?,
    val unreadCount: Int,
)
