package com.bluetalk.app.data

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Delivery lifecycle of an outgoing message, mirroring the familiar
 * messenger tick states: pending (queued, peer unreachable), sent
 * (written to the Bluetooth socket), delivered (acknowledged by the
 * peer's device) and read (peer opened the conversation).
 */
enum class MessageStatus { PENDING, SENT, DELIVERED, READ }

/** One chat per remote Bluetooth device, keyed by its MAC address. */
@Entity(tableName = "conversations")
data class Conversation(
    @PrimaryKey val address: String,
    val name: String,
    val lastActivity: Long,
)

@Entity(
    tableName = "messages",
    indices = [Index(value = ["conversationAddress", "timestamp"])],
)
data class Message(
    /** Random UUID generated by the sender; also used to de-duplicate re-sends. */
    @PrimaryKey val id: String,
    val conversationAddress: String,
    val body: String,
    val timestamp: Long,
    val isMine: Boolean,
    /** Only meaningful for outgoing messages. */
    val status: MessageStatus,
    /** Whether the local user has seen this message (drives the unread badge). */
    val isRead: Boolean,
)

/** Row shape for the conversation list: conversation plus preview and unread count. */
data class ConversationSummary(
    val address: String,
    val name: String,
    val lastActivity: Long,
    val lastMessage: String?,
    val lastMessageIsMine: Boolean?,
    val unreadCount: Int,
)
